name: docker_sign
on:
  push:
    branches: [ main ]
  steps:
    - name: checkout
      uses: actions/checkout@main
    - name: login to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ docker_env.docker_username }}
